### ISSUE TITLE
proof for claim for 0x0D1F568bcBEd9594366860153365Da855Cc46E5B

### ISSUE THREAD

**Issue by kirilusd** [pirl/governance#1]
this is proof:
![pirl](https://user-images.githubusercontent.com/48582254/100965994-9340c880-3534-11eb-9242-a396a2eb36de.png)

whallet from old network 0x0D1F568bcBEd9594366860153365Da855Cc46E5B

Wallet to send from new network : 5FeLHmTnk9jCosCCsnRudH8fhL6fM5WCsGoDTTELh1PcVDSp

**Comment by masterdubs** [comment]
Solved by   #https://github.com/pirl/governance/commit/6e5c41847e39ffd59c6a2a7c3d53f88aa20971bd
