### ISSUE TITLE
molchan 0xAF996c250fc8565DD18957184bC8e0fbF8C5b01e

### ISSUE THREAD

**Issue by molchanitsky** [pirl/governance#3]
<img width="1280" alt="Снимок экрана 2020-12-03 в 09 19 05" src="https://user-images.githubusercontent.com/31190041/101000176-2fcf8e80-3566-11eb-8948-e2bedea7bdf6.png">
<img width="1280" alt="Снимок экрана 2020-12-03 в 09 19 25" src="https://user-images.githubusercontent.com/31190041/101000188-34944280-3566-11eb-9a31-1bb4cdae3e80.png">

**Comment by masterdubs** [comment]
merged in validated, pending vote
